scenario_director:
  ros__parameters:
    pure_pursuit.lookahead_distance: 10.0
    pure_pursuit.min_lookahead: 4.0
    pure_pursuit.max_lookahead: 50.0
    pure_pursuit.lookahead_ratio: 0.2

local_path_planner:
  ros__parameters:
    pure_pursuit.lookahead_distance: 10.0
    pure_pursuit.min_lookahead: 4.0
    pure_pursuit.max_lookahead: 50.0
    pure_pursuit.lookahead_ratio: 0.2
