udp_receiver:
  ros__parameters:
    udp.recv_ip: "169.254.58.1"
    udp.ego_recv_port: 9090

    # NPC receive ports (vehicle_info)
    udp.npc1_recv_port: 9190
    udp.npc2_recv_port: 9290
    udp.npc3_recv_port: 9390
    udp.npc4_recv_port: 9490
    udp.npc5_recv_port: 9590
    udp.npc6_recv_port: 9690
    udp.npc7_recv_port: 9790
    udp.npc8_recv_port: 9890
    udp.npc9_recv_port: 9990

udp_sender:
  ros__parameters:
    udp.send_ip: "169.254.58.138"
    udp.ego_send_port: 9091

    # NPC send ports (ctrl_cmd)
    udp.npc1_send_port: 9191
    udp.npc2_send_port: 9291
    udp.npc3_send_port: 9391
    udp.npc4_send_port: 9491
    udp.npc5_send_port: 9591
    udp.npc6_send_port: 9691
    udp.npc7_send_port: 9791
    udp.npc8_send_port: 9891
    udp.npc9_send_port: 9991

camera_receiver:
  ros__parameters:
    udp.recv_ip: "169.254.58.1"

    # Front camera
    camera.front.port: 6666
    camera.front.enable: true

    # Front left camera
    camera.front_left.port: 7700
    camera.front_left.enable: true

    # Rear left camera
    camera.rear_left.port: 7755
    camera.rear_left.enable: true

    # Front right camera
    camera.front_right.port: 8800
    camera.front_right.enable: true

    # Rear right camera
    camera.rear_right.port: 8855
    camera.rear_right.enable: true
