udp_receiver:
  ros__parameters:
    udp.recv_ip: "192.132.72.1"
    udp.ego_recv_port: 9090
    udp.opponent_recv_port: 9091

udp_sender:
  ros__parameters:
    udp.send_ip: "192.132.72.138"
    udp.ego_send_port: 9093
    udp.npc_send_port: 9094

camera_receiver:
  ros__parameters:
    udp.recv_ip: "169.254.58.1"

    # Front camera
    camera.front.port: 6666
    camera.front.enable: true

    # Left front camera
    camera.left_front.port: 7700
    camera.left_front.enable: true

    # Left rear camera
    camera.left_rear.port: 7755
    camera.left_rear.enable: true

    # Right front camera
    camera.right_front.port: 8800
    camera.right_front.enable: true

    # Right rear camera
    camera.right_rear.port: 8855
    camera.right_rear.enable: true
